name: Run presubmit-test 2 copy

on:
  pull_request_review:
    types: [submitted]

jobs:

  test:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.event.pull_request.base.ref}}
