name: Run presubmit-test 2

on:
  pull_request_review:
    types: [submitted]

jobs:

  test:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello"
