name: Run presubmit

on:
  pull_request_review:
    types: [submitted]

jobs:

  test:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.event.pull_request.base.ref}}
